version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  my-app:
    image: dylancalo/my-docker-app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
    depends_on:
      - db
    ports:
      - "3000:3000"

  read-only-app:
    image: dylancalo/my-docker-app-read-only
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
    depends_on:
      - db
    ports:
      - "3001:3000"

